/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

 */
/*
 importa el paquete de vista en donde esta la interfaz de usuario
 */
package Views.interfaz;

import otros.Conectado_db;
import java.sql.*;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.nomina.calculos;
import static sun.management.Agent.warning;

/**
 *
 * @author Sena
 */
public class Formulario_empleado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Formulario_empleado() {
        initComponents();
        login.setVisible(true);
        registro.setVisible(false);
        secretaria.setVisible(false);
        gerente.setVisible(false);
        Ver_datos_planilla.setVisible(false);
        Mail.setVisible(false);
        registrarse.setVisible(false);
        CRUD.setVisible(false);
        Planilla.setVisible(false);
    }

    Calendar MiCalendario = Calendar.getInstance();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField19 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        registro = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        secretaria = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        gerente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton23 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        Mail = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton12 = new javax.swing.JButton();
        registrarse = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField15 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        CRUD = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        Planilla = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        Ver_datos_planilla = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton29 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton31 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton30 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();

        jTextField19.setText("jTextField19");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        registro.setBackground(new java.awt.Color(153, 255, 153));
        registro.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-user-icon.png"))); // NOI18N
        jButton1.setText("Secretaria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        registro.add(jButton1);
        jButton1.setBounds(370, 480, 140, 70);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        jButton2.setText("gerente");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        registro.add(jButton2);
        jButton2.setBounds(220, 480, 130, 70);

        jButton7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ima2.png"))); // NOI18N
        jButton7.setText("Ingresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        registro.add(jButton7);
        jButton7.setBounds(60, 480, 130, 70);

        jButton21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/descarga.jpg"))); // NOI18N
        jButton21.setText("Registrate");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        registro.add(jButton21);
        jButton21.setBounds(530, 480, 150, 70);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel6.setText("!BIENVENIDOS!");
        registro.add(jLabel6);
        jLabel6.setBounds(220, 50, 310, 50);

        jLabel24.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel24.setText("Sistema de nomina de nomina y registro de empleados");
        registro.add(jLabel24);
        jLabel24.setBounds(170, 110, 400, 26);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ASPEL.png"))); // NOI18N
        registro.add(jLabel37);
        jLabel37.setBounds(200, 210, 310, 140);

        getContentPane().add(registro);
        registro.setBounds(0, 0, 800, 800);

        secretaria.setBackground(new java.awt.Color(2, 204, 71));
        secretaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        secretaria.setToolTipText("");
        secretaria.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                secretariaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        secretaria.setLayout(null);

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        secretaria.add(jButton3);
        jButton3.setBounds(190, 480, 100, 40);

        jButton13.setText("Atras");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        secretaria.add(jButton13);
        jButton13.setBounds(460, 480, 100, 40);

        jPanel6.setBackground(new java.awt.Color(167, 240, 180));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE EMPLEADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 14))); // NOI18N
        jPanel6.setLayout(null);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel6.add(jTextField4);
        jTextField4.setBounds(330, 240, 300, 30);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel6.add(jTextField3);
        jTextField3.setBounds(330, 180, 300, 30);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel6.add(jTextField2);
        jTextField2.setBounds(330, 120, 300, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel6.add(jTextField1);
        jTextField1.setBounds(330, 70, 300, 30);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel4.setText("SALARIO");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(70, 250, 90, 22);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel3.setText("CARGO");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(70, 190, 70, 22);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel2.setText("NOMBRE Y APELLIDOS");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(70, 130, 190, 22);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel1.setText("CODIGO");
        jPanel6.add(jLabel1);
        jLabel1.setBounds(70, 70, 80, 22);

        secretaria.add(jPanel6);
        jPanel6.setBounds(50, 110, 720, 330);

        jLabel34.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        jLabel34.setText("REGISTRO DE EMPLEADOS");
        secretaria.add(jLabel34);
        jLabel34.setBounds(220, 30, 400, 30);

        jButton28.setText("Control empleados");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        secretaria.add(jButton28);
        jButton28.setBounds(580, 480, 130, 40);

        jButton26.setText("Actualizar");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        secretaria.add(jButton26);
        jButton26.setBounds(320, 480, 100, 40);

        getContentPane().add(secretaria);
        secretaria.setBounds(0, 0, 840, 570);

        login.setBackground(new java.awt.Color(1, 179, 32));
        login.setMinimumSize(new java.awt.Dimension(700, 500));
        login.setPreferredSize(new java.awt.Dimension(650, 620));
        login.setLayout(null);

        jButton11.setText("Atras");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        login.add(jButton11);
        jButton11.setBounds(550, 630, 70, 40);

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel19.setText("Inicio de Sesión");
        login.add(jLabel19);
        jLabel19.setBounds(270, 90, 280, 40);

        jPanel4.setBackground(new java.awt.Color(131, 240, 160));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jButton8.setText("ENTRAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(70, 280, 300, 50);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(70, 190, 300, 40);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 17, 17));
        jLabel5.setText("Contraseña");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(70, 160, 90, 22);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField7);
        jTextField7.setBounds(70, 100, 300, 40);

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(29, 17, 17));
        jLabel23.setText("Usuario");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(70, 70, 90, 22);

        login.add(jPanel4);
        jPanel4.setBounds(160, 180, 440, 370);

        jButton25.setText("Registrate");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        login.add(jButton25);
        jButton25.setBounds(640, 630, 110, 40);

        getContentPane().add(login);
        login.setBounds(0, 10, 790, 700);

        gerente.setBackground(new java.awt.Color(0, 212, 52));
        gerente.setLayout(null);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CARGO", "SALARIO"
            }
        ));
        jTable1.setDoubleBuffered(true);
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(154, 146, 146));
        jTable1.setOpaque(false);
        jTable1.setRequestFocusEnabled(false);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gerente.add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 610, 230);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente\t", "Secretaria" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gerente.add(jComboBox1);
        jComboBox1.setBounds(420, 30, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("Seleccione rol");
        gerente.add(jLabel7);
        jLabel7.setBounds(280, 40, 120, 20);

        jPanel3.setBackground(new java.awt.Color(200, 240, 183));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 14))); // NOI18N
        jPanel3.setLayout(null);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(20, 80, 190, 30);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(20, 30, 190, 30);

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton6.setText("Buscar por ID");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(240, 80, 160, 30);

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton5.setText("Buscar por nombre");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(240, 30, 160, 30);

        gerente.add(jPanel3);
        jPanel3.setBounds(20, 400, 430, 130);
        gerente.add(jSeparator1);
        jSeparator1.setBounds(0, 320, 0, 2);
        gerente.add(jSeparator2);
        jSeparator2.setBounds(0, 350, 660, 10);

        jButton23.setText("Atras");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        gerente.add(jButton23);
        jButton23.setBounds(190, 710, 100, 40);

        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gerente.add(jButton9);
        jButton9.setBounds(340, 710, 100, 40);

        jButton15.setText("Actualizar");
        gerente.add(jButton15);
        jButton15.setBounds(490, 580, 140, 40);

        jButton24.setText("Eliminar");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        gerente.add(jButton24);
        jButton24.setBounds(490, 520, 140, 40);

        jButton4.setText("Mostrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gerente.add(jButton4);
        jButton4.setBounds(490, 400, 140, 40);

        jButton32.setText("Control de empleados");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        gerente.add(jButton32);
        jButton32.setBounds(490, 460, 140, 40);

        getContentPane().add(gerente);
        gerente.setBounds(60, 50, 660, 800);

        Mail.setLayout(null);

        jLabel8.setText("Desde");
        Mail.add(jLabel8);
        jLabel8.setBounds(40, 110, 120, 14);

        jLabel9.setText("Para");
        Mail.add(jLabel9);
        jLabel9.setBounds(40, 170, 22, 14);

        jLabel10.setText("Asunto");
        Mail.add(jLabel10);
        jLabel10.setBounds(40, 220, 34, 14);

        jTextField8.setText("jTextField8");
        Mail.add(jTextField8);
        jTextField8.setBounds(160, 110, 320, 20);

        jTextField9.setText("jTextField9");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        Mail.add(jTextField9);
        jTextField9.setBounds(160, 160, 320, 20);

        jTextField10.setText("jTextField10");
        Mail.add(jTextField10);
        jTextField10.setBounds(160, 210, 320, 20);

        jButton10.setText("Enviar");
        Mail.add(jButton10);
        jButton10.setBounds(510, 100, 150, 140);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        Mail.add(jScrollPane2);
        jScrollPane2.setBounds(40, 270, 620, 200);

        jLabel11.setText("seleccione rol");
        Mail.add(jLabel11);
        jLabel11.setBounds(40, 30, 110, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente\t", "Secretaria" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        Mail.add(jComboBox2);
        jComboBox2.setBounds(180, 30, 210, 20);

        jButton12.setText("Salir");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Mail.add(jButton12);
        jButton12.setBounds(580, 490, 80, 23);

        getContentPane().add(Mail);
        Mail.setBounds(0, 0, 700, 540);

        registrarse.setBackground(new java.awt.Color(6, 170, 68));
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registrarse.setLayout(null);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        registrarse.add(jTextField13);
        jTextField13.setBounds(310, 210, 310, 30);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.jpeg"))); // NOI18N
        jButton16.setText("Guardar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        registrarse.add(jButton16);
        jButton16.setBounds(250, 520, 130, 50);

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        registrarse.add(jTextField11);
        jTextField11.setBounds(310, 160, 310, 30);

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel20.setText("Registrate");
        registrarse.add(jLabel20);
        jLabel20.setBounds(300, 10, 200, 50);

        jPanel1.setBackground(new java.awt.Color(179, 252, 175));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 16))); // NOI18N
        jPanel1.setLayout(null);

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField14);
        jTextField14.setBounds(270, 30, 310, 30);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel13.setText("Nombre(s)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 40, 110, 20);

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel21.setText("Apellido(s)");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(40, 90, 110, 20);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setText("E-mail");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 130, 70, 25);

        registrarse.add(jPanel1);
        jPanel1.setBounds(40, 80, 690, 180);

        jPanel2.setBackground(new java.awt.Color(186, 240, 175));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 16))); // NOI18N
        jPanel2.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel12.setText("Rol");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 40, 40, 25);

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel16.setText("Usuario");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 80, 70, 25);

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel17.setText("Contraseña");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(30, 130, 100, 25);
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(290, 130, 310, 30);
        jPanel2.add(jTextField15);
        jTextField15.setBounds(290, 90, 310, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secretaria", "Gerente" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(290, 40, 310, 30);

        registrarse.add(jPanel2);
        jPanel2.setBounds(40, 280, 690, 190);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel15.setText("Apellido(s)");
        registrarse.add(jLabel15);
        jLabel15.setBounds(90, 160, 110, 20);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ima4.png"))); // NOI18N
        jButton17.setText("Atras");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        registrarse.add(jButton17);
        jButton17.setBounds(420, 520, 130, 50);

        getContentPane().add(registrarse);
        registrarse.setBounds(0, 0, 775, 700);

        CRUD.setBackground(new java.awt.Color(78, 156, 89));
        CRUD.setLayout(null);

        jButton14.setText("ACTUALIZAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        CRUD.add(jButton14);
        jButton14.setBounds(120, 310, 200, 110);

        jButton18.setText("ELIMINAR");
        CRUD.add(jButton18);
        jButton18.setBounds(390, 310, 180, 110);

        jButton19.setText("CREAR");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        CRUD.add(jButton19);
        jButton19.setBounds(120, 160, 200, 110);

        jButton20.setText("CONSULTAR");
        CRUD.add(jButton20);
        jButton20.setBounds(390, 160, 180, 110);

        getContentPane().add(CRUD);
        CRUD.setBounds(0, 0, 700, 560);

        Planilla.setBackground(new java.awt.Color(2, 240, 78));
        Planilla.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(171, 240, 169));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS A INGRESAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N
        jPanel5.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel18.setText("NETO A PAGAR");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(340, 320, 130, 14);

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel25.setText("CODIGO");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(40, 70, 80, 22);

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel26.setText("NOMBRES ");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(40, 130, 80, 19);

        jLabel27.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel27.setText("CARGO");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(40, 190, 80, 22);

        jLabel28.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel28.setText("TURNO");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(40, 250, 80, 22);

        jLabel29.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel29.setText("AREA");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(40, 310, 80, 22);

        jLabel30.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel30.setText("SUELDO");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(340, 130, 80, 20);

        jLabel31.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel31.setText("BONIFICACION");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(340, 190, 130, 14);

        jLabel32.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel32.setText("DESCUENTO");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(340, 250, 110, 14);
        jPanel5.add(jTextField12);
        jTextField12.setBounds(150, 70, 170, 30);
        jPanel5.add(jTextField16);
        jTextField16.setBounds(150, 120, 170, 30);
        jPanel5.add(jTextField27);
        jTextField27.setBounds(480, 120, 170, 30);
        jPanel5.add(jTextField28);
        jTextField28.setBounds(480, 180, 170, 30);
        jPanel5.add(jTextField29);
        jTextField29.setBounds(480, 240, 170, 30);
        jPanel5.add(jTextField30);
        jTextField30.setBounds(480, 310, 170, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "EMPLEADO", "OBRERO", " " }));
        jPanel5.add(jComboBox4);
        jComboBox4.setBounds(150, 190, 170, 30);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "MAÑANA", "TARDE", "NOCHE" }));
        jPanel5.add(jComboBox5);
        jComboBox5.setBounds(150, 250, 170, 30);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "GERENCIA", "CONTABILIDAD", "LOGISTICA", "COMPUTO", "RECURSOS HUMANOS", " " }));
        jPanel5.add(jComboBox6);
        jComboBox6.setBounds(150, 310, 170, 30);

        Planilla.add(jPanel5);
        jPanel5.setBounds(20, 130, 690, 430);

        jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        jLabel33.setText("CONTROL DE PLANILLA");
        Planilla.add(jLabel33);
        jLabel33.setBounds(180, 30, 380, 40);

        jButton22.setText("Guardar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        Planilla.add(jButton22);
        jButton22.setBounds(140, 600, 120, 40);

        jButton27.setText("SALIR");
        Planilla.add(jButton27);
        jButton27.setBounds(500, 600, 110, 40);

        jButton35.setText("Atras");
        Planilla.add(jButton35);
        jButton35.setBounds(310, 600, 110, 40);

        getContentPane().add(Planilla);
        Planilla.setBounds(0, 0, 730, 690);

        Ver_datos_planilla.setBackground(new java.awt.Color(2, 240, 64));
        Ver_datos_planilla.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE Y APELLIDOS", "CARGO", "TURNO", "AREA", "SUELDO", "BONIFICACION", "DESCUENTO", "NETO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        Ver_datos_planilla.add(jScrollPane3);
        jScrollPane3.setBounds(30, 90, 680, 150);

        jButton29.setText("Mostrar ");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        Ver_datos_planilla.add(jButton29);
        jButton29.setBounds(40, 580, 150, 40);

        jPanel7.setBackground(new java.awt.Color(152, 240, 161));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 14))); // NOI18N
        jPanel7.setLayout(null);

        jLabel36.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel36.setText("Buscar: ");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(20, 50, 53, 19);
        jPanel7.add(jTextField18);
        jTextField18.setBounds(80, 40, 200, 30);

        jButton31.setText("Buscar por Codigo");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton31);
        jButton31.setBounds(290, 40, 140, 30);

        Ver_datos_planilla.add(jPanel7);
        jPanel7.setBounds(30, 290, 680, 110);

        jPanel8.setBackground(new java.awt.Color(149, 240, 152));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenar elementos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 14))); // NOI18N
        jPanel8.setLayout(null);

        jLabel35.setText("Ordenar por: ");
        jPanel8.add(jLabel35);
        jLabel35.setBounds(20, 40, 70, 14);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "CODIGO", "NOMBRES Y APELLIDOS", "CARGO ", "TURNO", "AREA", "SUELDO", "BONIFICACION", "DESCUENTO", "NERO A PAGAR" }));
        jPanel8.add(jComboBox7);
        jComboBox7.setBounds(120, 30, 230, 30);

        Ver_datos_planilla.add(jPanel8);
        jPanel8.setBounds(30, 430, 680, 90);

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel22.setText("Control Planilla de empleados");
        Ver_datos_planilla.add(jLabel22);
        jLabel22.setBounds(190, 20, 340, 30);

        jPanel12.setBackground(new java.awt.Color(0, 240, 57));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        Ver_datos_planilla.add(jPanel12);
        jPanel12.setBounds(0, 60, 740, 210);

        jButton30.setText("Atras");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        Ver_datos_planilla.add(jButton30);
        jButton30.setBounds(550, 580, 150, 40);

        jButton33.setText("Salir");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        Ver_datos_planilla.add(jButton33);
        jButton33.setBounds(310, 580, 150, 40);

        getContentPane().add(Ver_datos_planilla);
        Ver_datos_planilla.setBounds(0, 0, 740, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        if (jTextField1.getText().trim().isEmpty() || jTextField2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese los valores");
        } else {
            try {
                Statement stmt = cn.createStatement();
                String ins = "INSERT INTO NOMINA VALUES(" + jTextField1.getText() + ",'" + jTextField2.getText() + "','" + jTextField3.getText() + "'," + jTextField4.getText() + ");";
                int r = stmt.executeUpdate(ins);
            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
            }

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            System.out.println("Accion" + "guarda los datos del empleado");
            System.out.println("Usuario: secretaria");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        secretaria.setVisible(true);
        gerente.setVisible(false);
        registro.setVisible(false);
        Mail.setVisible(false);

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Accion: " + "La secretaria ingresa a registrar los empleados");
        System.out.println("Usuario: secretaria");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gerente.setVisible(true);
        login.setVisible(false);
        registro.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String busquedaSQL = "SELECT * FROM nomina WHERE NOMBRE = '" + jTextField5.getText() + "';";

            rs = stmt.executeQuery(busquedaSQL);

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Object[] filas = new Object[jTable1.getColumnCount()];

            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
            }

            while (rs.next()) {

                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getInt(4);

                tableModel.addRow(filas);
            }
            rs.close();
            stmt.close();
            cn.close();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            System.out.println("Accion:" + "El usuario consulta el campo por nombre");
            System.out.println("Usuario: Gerente");

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String busquedaSQL = "SELECT * FROM nomina WHERE ID = '" + jTextField6.getText() + "';";

            rs = stmt.executeQuery(busquedaSQL);

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Object[] filas = new Object[jTable1.getColumnCount()];

            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
            }

            while (rs.next()) {

                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getInt(4);

                tableModel.addRow(filas);

            }
            rs.close();
            stmt.close();
            cn.close();
            Calendar MiCalendario = Calendar.getInstance();
            Date d = new Date();
            System.out.println("Accion:" + "El usuario consulta el campo por ID");
            System.out.println("Usuario: Gerente");
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        gerente.setVisible(false);
        secretaria.setVisible(false);
        login.setVisible(true);
        registro.setVisible(false);

        Date d = new Date();
        System.out.println("Ingreso el usuario secreria al sistema");
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        String user = jTextField7.getText();
        char[] ps = jPasswordField1.getPassword();
        String password = new String(ps);
        String rol = null;

        try {
            Statement stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM ROLES");

            while (rs.next()) {
                if (user.equals(rs.getString(2)) && password.equals(rs.getString(3))) {
                    rol = rs.getString(1);

                    if (rol.equals("Gerente")) {
                        login.setVisible(false);
                        gerente.setVisible(true);
                        registro.setVisible(false);
                        Ver_datos_planilla.setVisible(false);

                    } else if (rol.equals("secretaria")) {
                        login.setVisible(false);
                        gerente.setVisible(false);
                        secretaria.setVisible(true);
                        registro.setVisible(false);
                        Mail.setVisible(false);

                    }
                }

            }

        } catch (SQLException sqex) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            gerente.setVisible(true);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            registro.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void secretariaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_secretariaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_secretariaAncestorAdded

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            gerente.setVisible(true);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            registro.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        secretaria.setVisible(true);

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        secretaria.setVisible(false);
        registro.setVisible(false);
        gerente.setVisible(false);

        Calendar MiCalendario = Calendar.getInstance();
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("la secretaria se desconecto del sistema");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        char[] ps = jPasswordField2.getPassword();
        String password = new String(ps);
        String rol = null;

        if (jTextField14.getText().trim().isEmpty() || jTextField11.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese los valores");
        } else {

            try {
                Statement stmt = cn.createStatement();
                String ins = "INSERT INTO REGISTRARSE VALUES(" + jTextField14.getText() + jTextField11.getText() + ",'" + jTextField13.getText() + "','" + "'," + ");";
                int r = stmt.executeUpdate(ins);

            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, "Error, al registrar");
            }

            try {
                Statement stmt = cn.createStatement();
                String ins = "INSERT INTO ROLES VALUES(" + jTextField15.getText() + password + ",'" + jComboBox3.getSelectedItem() + "','" + "'," + ");";
                int r = stmt.executeUpdate(ins);

            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, "Error, al registrar");
            }

        }

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();
        try {
            Statement stmt = cn.createStatement();
            String ins = "UPDATE NOMINA SET NOMBRE(" + jTextField1.getText() + ",'" + jTextField2.getText() + "','" + jTextField3.getText() + "'," + jTextField4.getText() + ");";
            int r = stmt.executeUpdate(ins);

        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
        }

        gerente.setVisible(true);

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Accion" + "guarda los datos del empleado");
        System.out.println("Usuario: secretaria");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo Letras");

        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Letras");

        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo numeros");

        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo numeros");

        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        registrarse.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        registro.setVisible(true);
        gerente.setVisible(false);
        secretaria.setVisible(false);
        Mail.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        registrarse.setVisible(true);
        login.setVisible(false);
        secretaria.setVisible(false);
        gerente.setVisible(false);
        Mail.setVisible(false);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        gerente.setVisible(false);
        secretaria.setVisible(false);
        Mail.setVisible(false);

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        Planilla.setVisible(true);
        registro.setVisible(false);
        secretaria.setVisible(false);
        gerente.setVisible(false);
        Mail.setVisible(false);
        login.setVisible(false);
        CRUD.setVisible(false);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

        int sue = 0, boni = 0, neto = 0, rete = 0;
        switch (this.jComboBox4.getSelectedIndex()) {
            case 0:
                switch (this.jComboBox5.getSelectedIndex()) {
                    case 0:
                        sue = 1200;
                        break;
                    case 1:
                        sue = 1400;
                        break;
                    case 2:
                        sue = 1600;
                        break;
                }

            case 1:
                switch (this.jComboBox5.getSelectedIndex()) {
                    case 0:
                        sue = 700;
                        break;
                    case 1:
                        sue = 800;
                        break;
                    case 2:
                        sue = 1000;
                        break;
                }
        }

        //determinar la bonificacion
        switch (this.jComboBox6.getSelectedIndex()) {
            case 0:
                boni = sue * 25 / 100;
                break;
            case 1:
                boni = sue * 20 / 100;
                break;
            case 2:
                boni = sue * 18 / 100;
                break;
            case 3:
                boni = sue * 15 / 100;
                break;
            case 4:
                boni = sue * 12 / 100;
                break;
            case 5:
                boni = sue * 10 / 100;
                break;

        }

        //deteminar las retenciones
        switch (this.jComboBox5.getSelectedIndex()) {
            case 0:
                rete = sue * 12 / 100;
                break;
            case 1:
                rete = sue * 8 / 100;
                break;
            case 2:
                rete = sue * 6 / 100;
                break;

        }

        //determinar el neto apagar
        neto = boni + sue - rete;

        //mostrando datos
        this.jTextField27.setText("" + sue);
        this.jTextField28.setText("" + boni);
        this.jTextField29.setText("" + rete);
        this.jTextField30.setText("" + neto);

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        Ver_datos_planilla.setVisible(true);
        gerente.setVisible(false);

    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        gerente.setVisible(true);

    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Esta seguro que desea salir?", "Confirmación",
                JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_NO_OPTION) {
            login.setVisible(true);
            registro.setVisible(false);
            gerente.setVisible(false);
        }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        try {
            Statement stmt = cn.createStatement();
            String ins = "DELETE FROM NOMINA WHERE " + jTextField1.getText() + ",'" + jTextField2.getText() + "','" + jTextField3.getText() + "'," + jTextField4.getText() + ");";
            int r = stmt.executeUpdate(ins);
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
        }

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Accion" + "guarda los datos del empleado");
        System.out.println("Usuario: secretaria");

    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Esta seguro que desea salir?", "Confirmación",
                JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
            login.setVisible(false);
            registro.setVisible(true);
            gerente.setVisible(false);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        registro.setVisible(true);
        login.setVisible(false);
        secretaria.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String vt = null;
            vt = "SELECT * FROM nomina;";

            rs = stmt.executeQuery(vt);

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Object[] filas = new Object[jTable1.getColumnCount()];

            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
            }

            while (rs.next()) {
                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getInt(4);

                tableModel.addRow(filas);
            }
            rs.close();
            stmt.close();
            cn.close();
            Calendar MiCalendario = Calendar.getInstance();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            System.out.println("Accion:" + "el usuario consulta los datos");
            System.out.println("Usuario: gerente");

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String busquedaSQL = "SELECT * FROM CONTROL_PLANILLA WHERE  CODIGO = '" + jTextField8.getText() + "';";

            rs = stmt.executeQuery(busquedaSQL);

            DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
            Object[] filas = new Object[jTable2.getColumnCount()];

            for (int i = jTable2.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable2.getModel()).removeRow(i);
            }

            while (rs.next()) {

                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);
                filas[5] = rs.getInt(6);
                filas[6] = rs.getInt(7);
                filas[7] = rs.getInt(8);
                filas[8] = rs.getInt(9);

                tableModel.addRow(filas);

            }
            rs.close();
            stmt.close();
            cn.close();
            Calendar MiCalendario = Calendar.getInstance();
            Date d = new Date();
            System.out.println("Accion:" + "El usuario consulta el campo por ID");
            System.out.println("Usuario: Gerente");
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String vt = null;
            vt = "SELECT * FROM CONTROL_PLANILLA;";

            rs = stmt.executeQuery(vt);

            DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
            Object[] filas = new Object[jTable2.getColumnCount()];

            for (int i = jTable2.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable2.getModel()).removeRow(i);
            }

            while (rs.next()) {
                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getString(5);
                filas[5] = rs.getInt(6);
                filas[6] = rs.getInt(7);
                filas[7] = rs.getInt(8);
                filas[8] = rs.getInt(9);

                tableModel.addRow(filas);
            }
            rs.close();
            stmt.close();
            cn.close();
            Calendar MiCalendario = Calendar.getInstance();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            System.out.println("Accion:" + "el usuario consulta los datos");
            System.out.println("Usuario: gerente");

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();
        try {
            Statement stmt = cn.createStatement();
            String ins = "UPDATE CONTROL_PLANILLA SET = " + ", CODIGO = " + jTextField1 + ", NOMBRE = " + jTextField2 + ", CARGO = " + jTextField3 + ", SALARIO = " + jTextField3 + " WHERE ' );";
            int r = stmt.executeUpdate(ins);
            stmt.close();
            cn.close();

        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
        }

    }//GEN-LAST:event_jButton26ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        if (evt.getButton() == 1) {
            int fila = jTable1.getSelectedRow();
            try {
                Statement stmt = cn.createStatement();
                String ins = "SELECT * FROM NOMINA ID= " + jTable1.getValueAt(fila, 0);
                int r = stmt.executeUpdate(ins);
                ResultSet rs;
                String vt = null;
                rs = stmt.executeQuery(vt);

                jTextField1.setText(rs.getString("NOMBRE"));
                jTextField2.setText(rs.getString("CARGO"));
                jTextField3.setText(rs.getString("SALARIO"));

            } catch (SQLException we) {

            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Letras");

        }
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Letras");

        }
    }//GEN-LAST:event_jTextField11KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CRUD;
    private javax.swing.JPanel Mail;
    private javax.swing.JPanel Planilla;
    private javax.swing.JPanel Ver_datos_planilla;
    private javax.swing.JPanel gerente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel login;
    private javax.swing.JPanel registrarse;
    private javax.swing.JPanel registro;
    private javax.swing.JPanel secretaria;
    // End of variables declaration//GEN-END:variables
}
